<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('equipment')->insert([
            [
                'name' => 'Digital Blood Pressure Monitor',
                'description' => 'Digital blood pressure monitoring device.',
                'price' => 2500,
                'stock' => 50,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Digital Thermometer',
                'description' => 'Digital thermometer for accurate temperature measurement.',
                'price' => 800,
                'stock' => 75,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pulse Oximeter',
                'description' => 'Portable pulse oximeter for measuring oxygen saturation.',
                'price' => 1200,
                'stock' => 60,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stethoscope',
                'description' => 'Professional medical stethoscope.',
                'price' => 1800,
                'stock' => 40,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Glucose Monitoring Kit',
                'description' => 'Complete blood glucose monitoring kit.',
                'price' => 2000,
                'stock' => 45,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Surgical Face Masks (50 pcs)',
                'description' => 'Box of 50 disposable surgical face masks.',
                'price' => 600,
                'stock' => 100,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Disposable Medical Gloves (100 pcs)',
                'description' => 'Box of 100 disposable medical gloves.',
                'price' => 900,
                'stock' => 80,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'First Aid Kit',
                'description' => 'General-purpose medical first aid kit.',
                'price' => 1500,
                'stock' => 35,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Infrared Forehead Thermometer',
                'description' => 'Non-contact infrared thermometer.',
                'price' => 1300,
                'stock' => 50,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medical Examination Gown',
                'description' => 'Disposable medical examination gown.',
                'price' => 700,
                'stock' => 60,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nebulizer Machine',
                'description' => 'Portable nebulizer machine for respiratory treatment.',
                'price' => 3500,
                'stock' => 25,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Portable Oxygen Concentrator',
                'description' => 'Portable oxygen concentration device.',
                'price' => 35000,
                'stock' => 10,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manual Wheelchair',
                'description' => 'Manual wheelchair for patient mobility.',
                'price' => 12000,
                'stock' => 15,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Adjustable Walking Crutches',
                'description' => 'Adjustable medical walking crutches.',
                'price' => 2800,
                'stock' => 30,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medical Bedside Table',
                'description' => 'Medical bedside table for patient rooms.',
                'price' => 8500,
                'stock' => 12,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Digital Weighing Scale',
                'description' => 'Digital medical weighing scale.',
                'price' => 2200,
                'stock' => 40,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medical Suction Machine',
                'description' => 'Medical suction machine for clinical use.',
                'price' => 9500,
                'stock' => 15,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Examination Light',
                'description' => 'Adjustable medical examination light.',
                'price' => 6000,
                'stock' => 20,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IV Stand',
                'description' => 'Adjustable intravenous fluid stand.',
                'price' => 3000,
                'stock' => 25,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Disposable Syringes (50 pcs)',
                'description' => 'Pack of 50 disposable medical syringes.',
                'price' => 750,
                'stock' => 100,
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}