<?php

namespace Database\Seeders;

use App\Models\Medicine;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [
            [
                'name' => 'Paracetamol 500mg',
                'category' => 'Pain Relief',
                'description' => 'Used to relieve mild to moderate pain and reduce fever.',
                'price' => 2.00,
                'stock' => 500,
            ],
            [
                'name' => 'Paracetamol 650mg',
                'category' => 'Pain Relief',
                'description' => 'Higher strength paracetamol for pain and fever relief.',
                'price' => 3.00,
                'stock' => 450,
            ],
            [
                'name' => 'Ibuprofen 200mg',
                'category' => 'Pain Relief',
                'description' => 'Helps reduce pain, inflammation, and fever.',
                'price' => 4.00,
                'stock' => 300,
            ],
            [
                'name' => 'Ibuprofen 400mg',
                'category' => 'Pain Relief',
                'description' => 'Higher strength anti-inflammatory pain relief medicine.',
                'price' => 6.00,
                'stock' => 250,
            ],
            [
                'name' => 'Aspirin 75mg',
                'category' => 'Cardiovascular',
                'description' => 'Low-dose aspirin commonly used under medical guidance for cardiovascular protection.',
                'price' => 2.00,
                'stock' => 400,
            ],
            [
                'name' => 'Cetirizine 10mg',
                'category' => 'Allergy',
                'description' => 'Antihistamine used to relieve common allergy symptoms.',
                'price' => 3.00,
                'stock' => 350,
            ],
            [
                'name' => 'Loratadine 10mg',
                'category' => 'Allergy',
                'description' => 'Non-drowsy antihistamine for allergy symptom relief.',
                'price' => 4.00,
                'stock' => 280,
            ],
            [
                'name' => 'Fexofenadine 120mg',
                'category' => 'Allergy',
                'description' => 'Antihistamine used to treat allergy symptoms.',
                'price' => 7.00,
                'stock' => 220,
            ],
            [
                'name' => 'Omeprazole 20mg',
                'category' => 'Digestive',
                'description' => 'Reduces stomach acid and is commonly used for acid-related conditions.',
                'price' => 5.00,
                'stock' => 300,
            ],
            [
                'name' => 'Pantoprazole 40mg',
                'category' => 'Digestive',
                'description' => 'Proton pump inhibitor used to reduce stomach acid.',
                'price' => 6.00,
                'stock' => 250,
            ],
            [
                'name' => 'Esomeprazole 20mg',
                'category' => 'Digestive',
                'description' => 'Used to reduce stomach acid and manage acid reflux.',
                'price' => 7.00,
                'stock' => 200,
            ],
            [
                'name' => 'Antacid Suspension',
                'category' => 'Digestive',
                'description' => 'Liquid antacid for temporary relief from heartburn and indigestion.',
                'price' => 80.00,
                'stock' => 100,
            ],
            [
                'name' => 'Oral Saline',
                'category' => 'Hydration',
                'description' => 'Oral rehydration solution used to help replace fluids and electrolytes.',
                'price' => 15.00,
                'stock' => 500,
            ],
            [
                'name' => 'Zinc 20mg',
                'category' => 'Vitamins',
                'description' => 'Zinc supplement supporting normal immune and metabolic functions.',
                'price' => 3.00,
                'stock' => 350,
            ],
            [
                'name' => 'Vitamin C 500mg',
                'category' => 'Vitamins',
                'description' => 'Vitamin C supplement supporting normal immune function.',
                'price' => 4.00,
                'stock' => 400,
            ],
            [
                'name' => 'Vitamin D3',
                'category' => 'Vitamins',
                'description' => 'Vitamin D supplement supporting bones and normal calcium absorption.',
                'price' => 8.00,
                'stock' => 250,
            ],
            [
                'name' => 'Calcium + Vitamin D',
                'category' => 'Vitamins',
                'description' => 'Supplement containing calcium and vitamin D for bone health.',
                'price' => 6.00,
                'stock' => 300,
            ],
            [
                'name' => 'Multivitamin Tablets',
                'category' => 'Vitamins',
                'description' => 'Combination vitamin and mineral supplement.',
                'price' => 5.00,
                'stock' => 350,
            ],
            [
                'name' => 'Iron + Folic Acid',
                'category' => 'Supplements',
                'description' => 'Iron and folic acid supplement used when additional dietary supplementation is needed.',
                'price' => 4.00,
                'stock' => 280,
            ],
            [
                'name' => 'Folic Acid 5mg',
                'category' => 'Supplements',
                'description' => 'Folic acid supplement used under medical or nutritional guidance.',
                'price' => 2.00,
                'stock' => 400,
            ],
            [
                'name' => 'Azithromycin 500mg',
                'category' => 'Antibiotics',
                'description' => 'Prescription antibiotic used for certain bacterial infections.',
                'price' => 15.00,
                'stock' => 120,
            ],
            [
                'name' => 'Amoxicillin 500mg',
                'category' => 'Antibiotics',
                'description' => 'Prescription antibiotic used to treat certain bacterial infections.',
                'price' => 8.00,
                'stock' => 150,
            ],
            [
                'name' => 'Cephalexin 500mg',
                'category' => 'Antibiotics',
                'description' => 'Cephalosporin antibiotic used for certain bacterial infections.',
                'price' => 10.00,
                'stock' => 100,
            ],
            [
                'name' => 'Metronidazole 400mg',
                'category' => 'Antibiotics',
                'description' => 'Antimicrobial medicine used for certain bacterial and parasitic infections.',
                'price' => 5.00,
                'stock' => 180,
            ],
            [
                'name' => 'Doxycycline 100mg',
                'category' => 'Antibiotics',
                'description' => 'Antibiotic used for a range of bacterial infections under medical supervision.',
                'price' => 7.00,
                'stock' => 150,
            ],
            [
                'name' => 'Acyclovir 400mg',
                'category' => 'Antiviral',
                'description' => 'Antiviral medicine used for certain herpes virus infections.',
                'price' => 12.00,
                'stock' => 100,
            ],
            [
                'name' => 'Clotrimazole Cream',
                'category' => 'Skin Care',
                'description' => 'Topical antifungal cream for certain fungal skin infections.',
                'price' => 45.00,
                'stock' => 120,
            ],
            [
                'name' => 'Miconazole Cream',
                'category' => 'Skin Care',
                'description' => 'Topical antifungal medicine for certain fungal skin conditions.',
                'price' => 55.00,
                'stock' => 100,
            ],
            [
                'name' => 'Hydrocortisone Cream',
                'category' => 'Skin Care',
                'description' => 'Topical corticosteroid used for certain inflammatory skin conditions.',
                'price' => 40.00,
                'stock' => 100,
            ],
            [
                'name' => 'Povidone-Iodine Solution',
                'category' => 'Antiseptic',
                'description' => 'Antiseptic solution for cleaning and disinfecting skin.',
                'price' => 90.00,
                'stock' => 80,
            ],
            [
                'name' => 'Antiseptic Cream',
                'category' => 'Antiseptic',
                'description' => 'Topical antiseptic cream for minor skin injuries.',
                'price' => 50.00,
                'stock' => 100,
            ],
            [
                'name' => 'Cough Syrup',
                'category' => 'Cough & Cold',
                'description' => 'Liquid medicine intended for symptomatic cough relief.',
                'price' => 120.00,
                'stock' => 90,
            ],
            [
                'name' => 'Expectorant Syrup',
                'category' => 'Cough & Cold',
                'description' => 'Cough medicine intended to help loosen mucus.',
                'price' => 110.00,
                'stock' => 80,
            ],
            [
                'name' => 'Salbutamol Inhaler',
                'category' => 'Respiratory',
                'description' => 'Inhaled medicine used under medical guidance to relieve certain breathing symptoms.',
                'price' => 180.00,
                'stock' => 60,
            ],
            [
                'name' => 'Nasal Saline Spray',
                'category' => 'Respiratory',
                'description' => 'Saline nasal spray used to moisturize and clear nasal passages.',
                'price' => 100.00,
                'stock' => 100,
            ],
            [
                'name' => 'Decongestant Tablets',
                'category' => 'Cough & Cold',
                'description' => 'Medicine intended to temporarily relieve nasal congestion.',
                'price' => 4.00,
                'stock' => 200,
            ],
            [
                'name' => 'Eye Lubricant Drops',
                'category' => 'Eye Care',
                'description' => 'Lubricating eye drops for temporary relief of dry eyes.',
                'price' => 150.00,
                'stock' => 70,
            ],
            [
                'name' => 'Antibiotic Eye Drops',
                'category' => 'Eye Care',
                'description' => 'Prescription eye drops used for certain bacterial eye infections.',
                'price' => 130.00,
                'stock' => 60,
            ],
            [
                'name' => 'Ear Drops',
                'category' => 'Ear Care',
                'description' => 'Ear drops used for selected ear-related symptoms and conditions.',
                'price' => 100.00,
                'stock' => 70,
            ],
            [
                'name' => 'ORS Orange',
                'category' => 'Hydration',
                'description' => 'Orange-flavored oral rehydration solution for replacing fluids and electrolytes.',
                'price' => 20.00,
                'stock' => 400,
            ],
            [
                'name' => 'ORS Lemon',
                'category' => 'Hydration',
                'description' => 'Lemon-flavored oral rehydration solution for replacing fluids and electrolytes.',
                'price' => 20.00,
                'stock' => 400,
            ],
            [
                'name' => 'Loperamide 2mg',
                'category' => 'Digestive',
                'description' => 'Medicine used to reduce symptoms of acute diarrhea.',
                'price' => 3.00,
                'stock' => 180,
            ],
            [
                'name' => 'Domperidone 10mg',
                'category' => 'Digestive',
                'description' => 'Medicine used under medical guidance for certain nausea and digestive symptoms.',
                'price' => 3.00,
                'stock' => 200,
            ],
            [
                'name' => 'Ondansetron 4mg',
                'category' => 'Digestive',
                'description' => 'Medicine used under medical supervision to help prevent nausea and vomiting.',
                'price' => 8.00,
                'stock' => 150,
            ],
            [
                'name' => 'Simethicone Tablets',
                'category' => 'Digestive',
                'description' => 'Used to relieve symptoms associated with excess gas.',
                'price' => 3.00,
                'stock' => 180,
            ],
            [
                'name' => 'Lactulose Syrup',
                'category' => 'Digestive',
                'description' => 'Laxative syrup used for constipation under appropriate guidance.',
                'price' => 140.00,
                'stock' => 80,
            ],
            [
                'name' => 'Diclofenac Gel',
                'category' => 'Pain Relief',
                'description' => 'Topical anti-inflammatory gel for certain muscle and joint pain.',
                'price' => 90.00,
                'stock' => 100,
            ],
            [
                'name' => 'Muscle Relief Balm',
                'category' => 'Pain Relief',
                'description' => 'Topical balm intended for temporary relief of minor muscle discomfort.',
                'price' => 70.00,
                'stock' => 120,
            ],
            [
                'name' => 'Calamine Lotion',
                'category' => 'Skin Care',
                'description' => 'Topical lotion used to soothe minor skin irritation and itching.',
                'price' => 75.00,
                'stock' => 100,
            ],
            [
                'name' => 'Petroleum Jelly',
                'category' => 'Skin Care',
                'description' => 'Skin protectant and moisturizer for dry or irritated skin.',
                'price' => 60.00,
                'stock' => 150,
            ],
        ];

        foreach ($medicines as $medicine) {
            Medicine::updateOrCreate(
                ['name' => $medicine['name']],
                $medicine
            );
        }
    }
}