<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        $patients = [
            [
                'id' => 1,
                'user_id' => 21,
                'phone' => '01799846519',
                'date_of_birth' => '2004-02-29',
                'gender' => 'Female',
                'blood_group' => 'O-',
                'zone' => 'Uttara',
                'address_line' => 'House 46, Road 7',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01842681330',
            ],
            [
                'id' => 2,
                'user_id' => 22,
                'phone' => '01779873016',
                'date_of_birth' => '1986-07-03',
                'gender' => 'Female',
                'blood_group' => 'B-',
                'zone' => 'Banani',
                'address_line' => 'House 40, Road 6',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01889000630',
            ],
            [
                'id' => 3,
                'user_id' => 25,
                'phone' => '01732234754',
                'date_of_birth' => '1979-01-01',
                'gender' => 'Female',
                'blood_group' => 'O-',
                'zone' => 'Banani',
                'address_line' => 'House 13, Road 3',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01898908229',
            ],
            [
                'id' => 4,
                'user_id' => 27,
                'phone' => '01739853458',
                'date_of_birth' => '1974-02-06',
                'gender' => 'Male',
                'blood_group' => 'AB-',
                'zone' => 'Banasree',
                'address_line' => 'House 22, Road 19',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01837374728',
            ],
            [
                'id' => 5,
                'user_id' => 28,
                'phone' => '01735363326',
                'date_of_birth' => '1979-11-01',
                'gender' => 'Female',
                'blood_group' => 'AB-',
                'zone' => 'Dhanmondi',
                'address_line' => 'House 28, Road 9',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01894130390',
            ],
            [
                'id' => 6,
                'user_id' => 29,
                'phone' => '01717721741',
                'date_of_birth' => '1983-08-11',
                'gender' => 'Male',
                'blood_group' => 'A-',
                'zone' => 'Mirpur',
                'address_line' => 'House 15, Road 14',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01890796382',
            ],
            [
                'id' => 7,
                'user_id' => 30,
                'phone' => '01736876774',
                'date_of_birth' => '1990-07-19',
                'gender' => 'Female',
                'blood_group' => 'A+',
                'zone' => 'Uttara',
                'address_line' => 'House 32, Road 8',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01821075103',
            ],
            [
                'id' => 8,
                'user_id' => 53,
                'phone' => '01791828566',
                'date_of_birth' => '1991-08-04',
                'gender' => 'Male',
                'blood_group' => 'B-',
                'zone' => 'Banani',
                'address_line' => 'House 13, Road 5',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01860037393',
            ],
            [
                'id' => 9,
                'user_id' => 54,
                'phone' => '01762701005',
                'date_of_birth' => '1984-10-03',
                'gender' => 'Female',
                'blood_group' => 'A-',
                'zone' => 'Mirpur',
                'address_line' => 'House 10, Road 6',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01861624463',
            ],
            [
                'id' => 10,
                'user_id' => 55,
                'phone' => '01725860654',
                'date_of_birth' => '1985-01-29',
                'gender' => 'Female',
                'blood_group' => 'B-',
                'zone' => 'Mirpur',
                'address_line' => 'House 13, Road 18',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01895073817',
            ],
            [
                'id' => 11,
                'user_id' => 56,
                'phone' => '01773056187',
                'date_of_birth' => '2005-06-12',
                'gender' => 'Female',
                'blood_group' => 'B+',
                'zone' => 'Mirpur',
                'address_line' => 'House 2, Road 6',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01848668860',
            ],
            [
                'id' => 12,
                'user_id' => 23,
                'phone' => '01748699015',
                'date_of_birth' => '1972-10-17',
                'gender' => 'Female',
                'blood_group' => 'O-',
                'zone' => 'Mirpur',
                'address_line' => 'House 31, Road 12',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01846032498',
            ],
            [
                'id' => 13,
                'user_id' => 24,
                'phone' => '01771060931',
                'date_of_birth' => '2003-12-06',
                'gender' => 'Male',
                'blood_group' => 'A-',
                'zone' => 'Banani',
                'address_line' => 'House 35, Road 6',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01864618019',
            ],
            [
                'id' => 14,
                'user_id' => 26,
                'phone' => '01768252382',
                'date_of_birth' => '1988-10-13',
                'gender' => 'Male',
                'blood_group' => 'B-',
                'zone' => 'Mirpur',
                'address_line' => 'House 36, Road 19',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01880406389',
            ],
            [
                'id' => 15,
                'user_id' => 51,
                'phone' => '01754078521',
                'date_of_birth' => '1986-04-19',
                'gender' => 'Female',
                'blood_group' => 'O-',
                'zone' => 'Banani',
                'address_line' => 'House 42, Road 7',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01815931773',
            ],
            [
                'id' => 16,
                'user_id' => 52,
                'phone' => '01712396456',
                'date_of_birth' => '1990-08-19',
                'gender' => 'Male',
                'blood_group' => 'O+',
                'zone' => 'Uttara',
                'address_line' => 'House 31, Road 19',
                'emergency_contact_name' => 'Emergency Contact',
                'emergency_contact_phone' => '01813385750',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::updateOrCreate(
                ['user_id' => $patient['user_id']],
                $patient
            );
        }
    }
}