@php
    $metrics = $report->metrics;
    $period = $metrics['period'];
    $reportTitle = $report->report_type === 'all'
        ? 'Complete Administrative Report'
        : ucfirst($report->report_type).' Administrative Report';
@endphp

<x-app-layout>
    <style>
        @media print {
            nav, .no-print { display: none !important; }
            body { background: #ffffff !important; }
            main { padding: 0 !important; }
            .report-sheet { border: 0 !important; box-shadow: none !important; }
            .print-avoid-break { break-inside: avoid; }
        }
    </style>

    <x-slot name="header">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
                <h2 class="text-xl font-semibold leading-tight text-gray-800">{{ $reportTitle }}</h2>
                <p class="mt-1 text-sm text-gray-500">
                    {{ $report->start_date->format('d M Y') }} - {{ $report->end_date->format('d M Y') }}
                </p>
            </div>
            <div class="no-print flex gap-3">
                <a
                    href="{{ route('admin.reports.index') }}"
                    class="inline-flex items-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 shadow-sm hover:bg-gray-50"
                >
                    Back to reports
                </a>
                <button
                    type="button"
                    onclick="window.print()"
                    class="inline-flex items-center rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700"
                >
                    Print / Save PDF
                </button>
            </div>
        </div>
    </x-slot>

    <main class="py-10">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            @if (session('success'))
                <div class="no-print mb-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">
                    {{ session('success') }}
                </div>
            @endif

            <article class="report-sheet space-y-8 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm sm:p-8">
                <header class="border-b border-gray-200 pb-6">
                    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                        <div>
                            <p class="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-600">Blood Sample Circulation Management System</p>
                            <h1 class="mt-2 text-3xl font-bold text-gray-900">{{ $reportTitle }}</h1>
                            <p class="mt-2 text-sm text-gray-500">Report #{{ $report->id }}</p>
                        </div>
                        <div class="text-sm text-gray-600 sm:text-right">
                            <p><span class="font-semibold text-gray-800">Period:</span> {{ $report->start_date->format('d M Y') }} - {{ $report->end_date->format('d M Y') }}</p>
                            <p class="mt-1"><span class="font-semibold text-gray-800">Generated:</span> {{ $report->created_at->format('d M Y, h:i A') }}</p>
                            <p class="mt-1"><span class="font-semibold text-gray-800">Administrator:</span> {{ $report->generatedBy?->name ?? 'Deleted administrator' }}</p>
                        </div>
                    </div>
                </header>

                <section class="print-avoid-break rounded-2xl border border-indigo-100 bg-indigo-50 p-6">
                    <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                        <h2 class="text-lg font-semibold text-indigo-950">AI operational analysis</h2>
                        @if ($report->ai_generated)
                            <span class="inline-flex w-fit rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">Generated by Gemini</span>
                        @else
                            <span class="inline-flex w-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-700">AI unavailable</span>
                        @endif
                    </div>

                    @if ($report->ai_summary)
                        <div class="mt-4 whitespace-pre-line text-sm leading-7 text-gray-800">{{ $report->ai_summary }}</div>
                    @else
                        <p class="mt-4 text-sm text-amber-800">
                            {{ $report->ai_error ?? 'No AI narrative was generated. The verified database metrics are available below.' }}
                        </p>
                    @endif
                </section>

                @if (isset($metrics['bottleneck']))
                    @php
                        $bottleneck = $metrics['bottleneck'];
                        $riskClass = match ($bottleneck['risk_level']) {
                            'high' => 'bg-red-100 text-red-700',
                            'medium' => 'bg-amber-100 text-amber-700',
                            'low' => 'bg-blue-100 text-blue-700',
                            default => 'bg-emerald-100 text-emerald-700',
                        };
                        $flagDetails = [
                            'approved_awaiting_collection' => [
                                'Approved, awaiting collection',
                                'Approved for more than '.$bottleneck['thresholds']['approved_to_collection_hours'].' hours without collection.',
                            ],
                            'collected_awaiting_transportation' => [
                                'Collected, no transportation',
                                'Collected samples that do not have a transportation record.',
                            ],
                            'transport_overdue' => [
                                'Transportation overdue',
                                'In transit for more than '.$bottleneck['thresholds']['maximum_in_transit_hours'].' hours.',
                            ],
                            'delivered_awaiting_review' => [
                                'Delivered, awaiting review',
                                'Delivered for more than '.$bottleneck['thresholds']['delivered_to_review_hours'].' hours without acceptance or rejection.',
                            ],
                            'accepted_awaiting_inventory' => [
                                'Accepted, not in inventory',
                                'Accepted samples with no physical storage record.',
                            ],
                            'duplicate_inventory_samples' => [
                                'Duplicate inventory records',
                                'Samples assigned to more than one inventory record.',
                            ],
                            'incomplete_transportation_records' => [
                                'Incomplete transport timestamps',
                                'Started or delivered records missing departure or arrival time.',
                            ],
                            'overdue_home_collections' => [
                                'Overdue home collections',
                                'Past scheduled home visits that are not marked collected.',
                            ],
                            'overbooked_laboratory_days' => [
                                'Overbooked laboratory days',
                                'Laboratory/date combinations exceeding configured daily capacity.',
                            ],
                        ];
                    @endphp

                    <section class="space-y-5 border-t border-gray-200 pt-8">
                        <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                            <div>
                                <h2 class="text-xl font-bold text-gray-900">AI bottleneck and anomaly audit</h2>
                                <p class="mt-1 text-sm text-gray-500">
                                    Cross-module checks for stuck samples, incomplete records and capacity problems.
                                </p>
                            </div>
                            <div class="flex items-center gap-2">
                                <span class="rounded-full px-3 py-1 text-xs font-semibold uppercase {{ $riskClass }}">
                                    {{ $bottleneck['risk_level'] }} risk
                                </span>
                                <span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold text-gray-700">
                                    {{ number_format($bottleneck['total_flags']) }} total flags
                                </span>
                            </div>
                        </div>

                        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                            @foreach ($flagDetails as $key => [$label, $description])
                                @php($count = $bottleneck['flags'][$key] ?? 0)
                                <div class="print-avoid-break rounded-xl border p-4 {{ $count > 0 ? 'border-amber-200 bg-amber-50' : 'border-emerald-200 bg-emerald-50' }}">
                                    <div class="flex items-start justify-between gap-4">
                                        <div>
                                            <h3 class="text-sm font-semibold text-gray-900">{{ $label }}</h3>
                                            <p class="mt-1 text-xs leading-5 text-gray-600">{{ $description }}</p>
                                        </div>
                                        <span class="text-2xl font-bold {{ $count > 0 ? 'text-amber-700' : 'text-emerald-700' }}">
                                            {{ number_format($count) }}
                                        </span>
                                    </div>
                                </div>
                            @endforeach
                        </div>

                        <p class="rounded-lg bg-gray-50 px-4 py-3 text-xs leading-5 text-gray-500">
                            A flag identifies a record requiring administrative review; it does not automatically mean the sample is invalid. One sample can produce more than one flag when multiple workflow stages are incomplete.
                        </p>
                    </section>
                @endif

                @if (isset($metrics['collection']))
                    @php($collection = $metrics['collection'])
                    <section class="print-avoid-break space-y-5">
                        <div>
                            <h2 class="text-xl font-bold text-gray-900">Sample collection activity</h2>
                            <p class="mt-1 text-sm text-gray-500">Requests, collections and laboratory quality reviews created or completed in the selected period.</p>
                        </div>

                        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
                            @foreach ([
                                'Requests' => $collection['requests_total'],
                                'Samples created' => $collection['samples_created'],
                                'Samples collected' => $collection['samples_collected'],
                                'Samples reviewed' => $collection['samples_reviewed'],
                                'Home requests' => $collection['home_collection_requests'],
                            ] as $label => $value)
                                <div class="rounded-xl border border-gray-200 p-4">
                                    <p class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $label }}</p>
                                    <p class="mt-2 text-2xl font-bold text-gray-900">{{ number_format($value) }}</p>
                                </div>
                            @endforeach
                        </div>

                        <div class="grid gap-5 lg:grid-cols-3">
                            @foreach ([
                                'Request status' => $collection['requests_by_status'],
                                'Sample status' => $collection['samples_by_status'],
                                'Home collection status' => $collection['home_collections_by_status'],
                            ] as $title => $rows)
                                <div class="overflow-hidden rounded-xl border border-gray-200">
                                    <h3 class="border-b border-gray-100 bg-gray-50 px-4 py-3 text-sm font-semibold text-gray-800">{{ $title }}</h3>
                                    <div class="divide-y divide-gray-100">
                                        @forelse ($rows as $status => $total)
                                            <div class="flex items-center justify-between px-4 py-3 text-sm">
                                                <span class="capitalize text-gray-600">{{ str_replace('_', ' ', $status) }}</span>
                                                <span class="font-semibold text-gray-900">{{ number_format($total) }}</span>
                                            </div>
                                        @empty
                                            <p class="px-4 py-3 text-sm text-gray-500">No records</p>
                                        @endforelse
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </section>
                @endif

                @if (isset($metrics['transportation']))
                    @php($transportation = $metrics['transportation'])
                    <section class="print-avoid-break space-y-5 border-t border-gray-200 pt-8">
                        <div>
                            <h2 class="text-xl font-bold text-gray-900">Transportation activity</h2>
                            <p class="mt-1 text-sm text-gray-500">Sample movements created in the selected period.</p>
                        </div>

                        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                            @foreach ([
                                'Transport records' => $transportation['records_total'],
                                'Delivered' => $transportation['delivered_count'],
                                'Average transit' => $transportation['average_transit_minutes'] === null ? 'N/A' : $transportation['average_transit_minutes'].' min',
                                'From patient homes' => $transportation['origin_breakdown']['patient_home'],
                            ] as $label => $value)
                                <div class="rounded-xl border border-gray-200 p-4">
                                    <p class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $label }}</p>
                                    <p class="mt-2 text-2xl font-bold text-gray-900">{{ is_numeric($value) ? number_format($value) : $value }}</p>
                                </div>
                            @endforeach
                        </div>

                        <div class="grid gap-5 lg:grid-cols-2">
                            @foreach ([
                                'Transportation status' => $transportation['by_status'],
                                'Destination laboratories' => $transportation['by_laboratory'],
                            ] as $title => $rows)
                                <div class="overflow-hidden rounded-xl border border-gray-200">
                                    <h3 class="border-b border-gray-100 bg-gray-50 px-4 py-3 text-sm font-semibold text-gray-800">{{ $title }}</h3>
                                    <div class="divide-y divide-gray-100">
                                        @forelse ($rows as $label => $total)
                                            <div class="flex items-center justify-between px-4 py-3 text-sm">
                                                <span class="capitalize text-gray-600">{{ str_replace('_', ' ', $label) }}</span>
                                                <span class="font-semibold text-gray-900">{{ number_format($total) }}</span>
                                            </div>
                                        @empty
                                            <p class="px-4 py-3 text-sm text-gray-500">No records</p>
                                        @endforelse
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </section>
                @endif

                @if (isset($metrics['inventory']))
                    @php($inventory = $metrics['inventory'])
                    <section class="print-avoid-break space-y-5 border-t border-gray-200 pt-8">
                        <div>
                            <h2 class="text-xl font-bold text-gray-900">Inventory activity</h2>
                            <p class="mt-1 text-sm text-gray-500">Current storage position and additions during the selected period.</p>
                        </div>

                        <div class="grid gap-4 sm:grid-cols-3">
                            @foreach ([
                                'Currently stored' => $inventory['current_stored_samples'],
                                'Added in period' => $inventory['added_during_period'],
                                'Accepted, not stored' => $inventory['accepted_not_stored'],
                            ] as $label => $value)
                                <div class="rounded-xl border border-gray-200 p-4">
                                    <p class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $label }}</p>
                                    <p class="mt-2 text-2xl font-bold text-gray-900">{{ number_format($value) }}</p>
                                </div>
                            @endforeach
                        </div>

                        <div class="grid gap-5 lg:grid-cols-2">
                            @foreach ([
                                'Storage locations' => $inventory['by_storage_location'],
                                'Refrigerators' => $inventory['by_refrigerator'],
                            ] as $title => $rows)
                                <div class="overflow-hidden rounded-xl border border-gray-200">
                                    <h3 class="border-b border-gray-100 bg-gray-50 px-4 py-3 text-sm font-semibold text-gray-800">{{ $title }}</h3>
                                    <div class="divide-y divide-gray-100">
                                        @forelse ($rows as $label => $total)
                                            <div class="flex items-center justify-between px-4 py-3 text-sm">
                                                <span class="text-gray-600">{{ $label ?: 'Not specified' }}</span>
                                                <span class="font-semibold text-gray-900">{{ number_format($total) }}</span>
                                            </div>
                                        @empty
                                            <p class="px-4 py-3 text-sm text-gray-500">No records</p>
                                        @endforelse
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </section>
                @endif

                @if (isset($metrics['laboratory']))
                    @php($laboratory = $metrics['laboratory'])
                    <section class="space-y-5 border-t border-gray-200 pt-8">
                        <div>
                            <h2 class="text-xl font-bold text-gray-900">Laboratory activity and capacity</h2>
                            <p class="mt-1 text-sm text-gray-500">Testing workload scheduled during the selected period.</p>
                        </div>

                        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
                            @foreach ([
                                'Active laboratories' => $laboratory['active_laboratories'],
                                'Period capacity' => $laboratory['total_period_capacity'],
                                'Scheduled tests' => $laboratory['scheduled_tests'],
                                'Available slots' => $laboratory['available_slots'],
                                'Utilization' => $laboratory['utilization_percent'].'%',
                            ] as $label => $value)
                                <div class="rounded-xl border border-gray-200 p-4">
                                    <p class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $label }}</p>
                                    <p class="mt-2 text-2xl font-bold text-gray-900">{{ is_numeric($value) ? number_format($value) : $value }}</p>
                                </div>
                            @endforeach
                        </div>

                        <div class="overflow-x-auto rounded-xl border border-gray-200">
                            <table class="min-w-full divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                    <tr>
                                        <th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">Laboratory</th>
                                        <th class="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-gray-500">Status</th>
                                        <th class="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-gray-500">Daily capacity</th>
                                        <th class="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-gray-500">Period capacity</th>
                                        <th class="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-gray-500">Scheduled</th>
                                        <th class="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-gray-500">Available</th>
                                        <th class="px-4 py-3 text-center text-xs font-semibold uppercase tracking-wide text-gray-500">Utilization</th>
                                    </tr>
                                </thead>
                                <tbody class="divide-y divide-gray-100 bg-white">
                                    @forelse ($laboratory['by_laboratory'] as $row)
                                        <tr>
                                            <td class="px-4 py-3 text-sm font-semibold text-gray-900">{{ $row['name'] }}</td>
                                            <td class="px-4 py-3 text-center text-sm">
                                                <span class="rounded-full px-2 py-1 text-xs font-semibold {{ $row['active'] ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-600' }}">
                                                    {{ $row['active'] ? 'Active' : 'Inactive' }}
                                                </span>
                                            </td>
                                            <td class="px-4 py-3 text-center text-sm text-gray-600">{{ number_format($row['daily_capacity']) }}</td>
                                            <td class="px-4 py-3 text-center text-sm text-gray-600">{{ number_format($row['period_capacity']) }}</td>
                                            <td class="px-4 py-3 text-center text-sm text-gray-600">{{ number_format($row['scheduled_tests']) }}</td>
                                            <td class="px-4 py-3 text-center text-sm text-gray-600">{{ number_format($row['available_slots']) }}</td>
                                            <td class="px-4 py-3 text-center text-sm font-semibold text-gray-900">{{ $row['utilization_percent'] }}%</td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7" class="px-4 py-8 text-center text-sm text-gray-500">No laboratories found.</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </section>
                @endif

                <footer class="border-t border-gray-200 pt-5 text-xs text-gray-500">
                    This report was generated from aggregate operational database records. AI commentary is advisory and should be verified against the displayed metrics.
                </footer>
            </article>
        </div>
    </main>
</x-app-layout>
